### ISSUE TITLE
Remove testify dep

### ISSUE THREAD

**Issue by srabraham** [wagslane/go-tinydate#1]
Hi Lane, thanks for this great package!

I'm wondering when the testify dependency removal might happen? I'd like to be able to tell my colleagues that this dep I'm bringing into our workspace (tinydate) doesn't bring in anything else.

I'd be happy to whip through this and change all those "assert." bits into simpler/uglier standard comparisons, if you're ok with that.

**Comment by wagslane** [comment]
Yeah feel free to open the PR!

**Comment by srabraham** [comment]
Awesome! No rush, but here is said PR: https://github.com/wagslane/go-tinydate/pull/2
Assuming that looks good, please make a new tag on this repo once it's merged

**Comment by wagslane** [comment]
resolved
